services:
  - type: web
    name: swiftshift-ui
    env: static
    staticPublishPath: swiftshift-ui/dist
    buildCommand: cd swiftshift-ui && npm install && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
